mysql:
  dev:
    host: 192.168.198.10
    port: 3306
    user: root
    password: '123456'
    database: certification
  pro:
    host: 113.45.195.128
    port: 3306
    user: root
    password: '123456'
    database: certification
